name: DeathListener
version: '${project.version}'
main: dev.farneser.deathlistener.DeathListener
api-version: '1.20'
author: farneser
commands:
  dlist:
    description: Show latest deaths
    usage: "/dlist [<page>]"
    permission: deathlistener.dlist
    aliases:
      - dl
      - d
permissions:
  deathlistener.dlist:
    default: op
    description: Allow command to show latest deaths for player
  deathlistener.dlist.admin:
    default: op
    description: Update command to show latest deaths for all players
    children:
      - death-list.dlist
