name: DeathListener
version: '${project.version}'
main: dev.farneser.deathlistener.DeathListener
api-version: '1.20'
author: farneser
commands:
  dlist:
    description: Show latest deaths
    usage: /dlist page
    permission: death-list.dlist
permissions:
  death-list.dlist:
    default: op
    description: Allow command to show latest deaths for player
  death-list.dlist.admin:
    default: op
    description: Update command to show latest deaths for all players
    children:
      - death-list.dlist
